import Head from 'next/head'
import Home from '../src/components/Home/Home';

export default function Home() {
  return (
  <div>
      <Head>
        <title>Whiteboard demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />

    </div>
  )
}
